# Generated by Django 3.2.6 on 2023-10-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='background',
            field=models.ImageField(upload_to='slider/%Y/%m/%d'),
        ),
    ]
