# Generated by Django 3.2.6 on 2023-11-05 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_schedule_scheduleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
