# Generated by Django 3.2.6 on 2023-11-05 16:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_slideritem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
