# Generated by Django 3.2.6 on 2023-11-06 13:28

import ckeditor.fields
import client.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_scheduleitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, client.models.Component, client.models.Model),
        ),
        migrations.CreateModel(
            name='FeauteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('feaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.feaute')),
            ],
            bases=(models.Model, client.models.Model),
        ),
    ]
