# Generated by Django 3.2.6 on 2023-11-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feaute',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='FeauteItem',
            new_name='FeatureItem',
        ),
        migrations.RenameField(
            model_name='featureitem',
            old_name='feaute',
            new_name='feature',
        ),
    ]
