# Generated by Django 3.2.6 on 2023-11-20 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0009_auto_20231111_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.page'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='isActive',
            field=models.BooleanField(choices=[(True, 'TRUE'), (False, 'FALSE')], default=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='isActive',
            field=models.BooleanField(choices=[(True, 'TRUE'), (False, 'FALSE')], default=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='isActive',
            field=models.BooleanField(choices=[(True, 'TRUE'), (False, 'FALSE')], default=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.page'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.page'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.page'),
        ),
    ]
