# Generated by Django 3.2.6 on 2023-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20231121_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
