# Generated by Django 3.2.6 on 2023-12-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20231213_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
